name: Gradle Package

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: clean test

      - name: Publish
        env:
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New Version ${NEW_VERSION}"
          ./gradlew -Pversion=${NEW_VERSION} publishToSonatype closeAndReleaseSonatypeStagingRepository

      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: 'main'
          token: ${{ secrets.PAT }}

      - name: Update readme
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          CURRENT_VERSION=$(gh api -X GET /repos/shinusuresh/productsup-client-spring-boot-starter/releases -F per_page=2 --jq '.[0].name')
          OLD_VERSION=$(gh api -X GET /repos/shinusuresh/productsup-client-spring-boot-starter/releases -F per_page=2 --jq '.[1].name')
          sed -i -e "s/${OLD_VERSION}/${CURRENT_VERSION}/g" readme.md      
          git config --global user.name 'Shinu Suresh'
          git config --global user.email '2842927+shinusuresh@users.noreply.github.com'
          git commit -am "Bumping version from $OLD_VERSION to $CURRENT_VERSION"          
          git push origin HEAD:main
